import { describe, expect, it } from "vitest";
import * as analytics from "@/lib/analytics";

describe("@/lib/analytics", () => {
  it("re-exports the public analytics API", () => {
    expect(Object.keys(analytics).sort()).toEqual([
      "HOUR_MS",
      "MIN_KALSHI_MOVES",
      "MIN_PAIRS",
      "RESEARCH_CSV_COLUMNS",
      "SIMPLE_EXCESS",
      "SMALL_EVENT_COUNT",
      "SMALL_SAMPLE",
      "TRADING_DAYS_PER_YEAR",
      "adjustedChanges",
      "adjustedLogChange",
      "alignSeries",
      "benchmarkCloses",
      "benchmarkReturnsByT",
      "binaryEntropy",
      "buildResearchRows",
      "computeChanges",
      "confidenceInterval95",
      "correlationStats",
      "crossCorrelation",
      "csvField",
      "detectJumps",
      "eventStudy",
      "eventWindowRows",
      "fitMarketModel",
      "impliedProbability",
      "incompleteBeta",
      "kalshiBenchmarkCorrelation",
      "kalshiRegression",
      "logReturns",
      "marketAdjustment",
      "mergeSeries",
      "neweyWestLags",
      "ols",
      "pearson",
      "probabilityChange",
      "realizedVolatility",
      "relativeVolume",
      "researchCsv",
      "rollingCorrelation",
      "rowsSince",
      "sampleFlag",
      "sampleStdDev",
      "tQuantile",
      "tTwoSidedP",
      "topOfHourCloses",
      "uncertaintyScore",
    ]);
  });
});
